USE [PDV]
GO
/****** Object:  Table [dbo].[PERFIL_FUNCIONALIDADE]    Script Date: 03/04/2008 14:28:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PERFIL_FUNCIONALIDADE](
	[ID_PERFIL] [int] NOT NULL,
	[ID_FUNCIONALIDADE] [int] NOT NULL,
 CONSTRAINT [PK_PERFIL_FUNCIONALIDADE] PRIMARY KEY CLUSTERED 
(
	[ID_PERFIL] ASC,
	[ID_FUNCIONALIDADE] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[PERFIL_FUNCIONALIDADE]  WITH CHECK ADD  CONSTRAINT [FK_FUNCIONALIDADE_PERFIL_FUNCIONALIDADE1] FOREIGN KEY([ID_FUNCIONALIDADE])
REFERENCES [dbo].[FUNCIONALIDADE] ([ID])
GO
ALTER TABLE [dbo].[PERFIL_FUNCIONALIDADE] CHECK CONSTRAINT [FK_FUNCIONALIDADE_PERFIL_FUNCIONALIDADE1]
GO
ALTER TABLE [dbo].[PERFIL_FUNCIONALIDADE]  WITH CHECK ADD  CONSTRAINT [FK_PERFIL_PERFIL_FUNCIONALIDADE] FOREIGN KEY([ID_PERFIL])
REFERENCES [dbo].[PERFIL_USUARIO] ([ID])
GO
ALTER TABLE [dbo].[PERFIL_FUNCIONALIDADE] CHECK CONSTRAINT [FK_PERFIL_PERFIL_FUNCIONALIDADE]