/*
   sábado, 17 de maio de 2008 16:44:06
   User: 
   Server: (local)
   Database: PDV
   Application: MS SQLEM - Data Tools
*/

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
EXECUTE sp_rename N'dbo.LOJA.ID_ESTOQUE_ATIVO', N'Tmp_ID_ESTOQUE_ATUAL', 'COLUMN'
GO
EXECUTE sp_rename N'dbo.LOJA.Tmp_ID_ESTOQUE_ATUAL', N'ID_ESTOQUE_ATUAL', 'COLUMN'
GO
COMMIT
