CREATE TABLE [dbo].[ACUMULADOR_NAO_FISCAL] (
	[ID] [int] NOT NULL ,
	[DESCRICAO] [varchar] (50) COLLATE Latin1_General_CI_AI NULL 
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[ACUMULADOR_NAO_FISCAL] ADD 
	CONSTRAINT [PK_ACUMULADOR_NAO_FISCAL] PRIMARY KEY  CLUSTERED 
	(
		[ID]
	)  ON [PRIMARY] 
GO

