/*
   quarta-feira, 23 de julho de 2008 22:40:36
   User: 
   Server: (local)
   Database: PDV
   Application: MS SQLEM - Data Tools
*/

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.TRANSACAO ADD
	ID_CLIENTE int NULL
GOALTER TABLE dbo.TRANSACAO WITH NOCHECK ADD CONSTRAINT	FK_TRANSACAO_CLIENTE FOREIGN KEY	(	ID_CLIENTE	) REFERENCES dbo.CLIENTE	(	ID	)GO
COMMIT
