/*
   terça-feira, 16 de setembro de 2008 21:15:24
   User: 
   Server: (local)
   Database: ENTERPRISE
   Application: MS SQLEM - Data Tools
*/

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
CREATE UNIQUE NONCLUSTERED INDEX IX_UNIQUE_CPFCNPJ_FORNECEDOR ON dbo.FORNECEDOR
	(
	CPF_CNPJ
	) ON [PRIMARY]
GO
COMMIT
