CREATE TABLE [dbo].[EVENTO_ITEM_PAGAMENTO_TROCA] (
	[LOJA] [numeric](18, 0) NOT NULL ,
	[COMPONENTE] [numeric](18, 0) NOT NULL ,
	[DATA_TRANSACAO] [datetime] NOT NULL ,
	[NUM_TRANSACAO] [numeric](18, 0) NOT NULL ,
	[NUM_EVENTO] [numeric](18, 0) NOT NULL ,
	[ID_OPERACAO] [varchar] (50) COLLATE Latin1_General_CI_AI NOT NULL 
) ON [PRIMARY]
GO



ALTER TABLE EVENTO_ITEM_PAGAMENTO_TROCA ADD CONSTRAINT FK_EV_IT_PAG_TROCA_EV_IT_PAG FOREIGN KEY(LOJA,COMPONENTE,NUM_TRANSACAO,DATA_TRANSACAO,NUM_EVENTO)
REFERENCES EVENTO_ITEM_PAGAMENTO(LOJA,COMPONENTE,NUM_TRANSACAO,DATA_TRANSACAO,NUM_EVENTO)