/*
   quarta-feira, 12 de novembro de 2008 21:06:03
   User: 
   Server: (local)
   Database: PDV
   Application: MS SQLEM - Data Tools
*/

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.ENTRADA_PRODUTO ADD
	QUANTIDADE_TOTAL numeric(18, 3) NOT NULL CONSTRAINT DF_ENTRADA_PRODUTO_QUANTIDADE_TOTAL DEFAULT 0
GO
COMMIT
