CREATE TABLE [dbo].[BANCO] (
  [ID] int NOT NULL,
  [DESCRICAO] varchar(50) COLLATE Latin1_General_CI_AI NULL,
  [SITUACAO] varchar(1) COLLATE Latin1_General_CI_AI NULL,
  PRIMARY KEY CLUSTERED ([ID])
)
ON [PRIMARY]
GO