/*
   terça-feira, 2 de junho de 2009 22:20:53
   User: 
   Server: (local)
   Database: ENTERPRISE
   Application: MS SQLEM - Data Tools
*/

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.MOVIMENTACAO_BANCARIA ADD
	SALDO_ANTERIOR_CONTA numeric(18, 0) NULL
GO
COMMIT
