/*
   quinta-feira, 23 de julho de 2009 20:24:05
   User: 
   Server: (local)
   Database: ENTERPRISE
   Application: MS SQLEM - Data Tools
*/

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.PARCELA_PLAN_PAGTO_CHEQUE_PRE
	DROP CONSTRAINT FK_PLAN_PAG_CHEQ_PRE_PARC
GO
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.PARCELA_PLAN_PAGTO_CHEQUE_PRE WITH NOCHECK ADD CONSTRAINT
	FK_PARCELA_PLAN_PAGTO_CHEQUE_PRE_PLANO_PAGAMENTO_APRAZO FOREIGN KEY
	(
	ID_PLANO
	) REFERENCES dbo.PLANO_PAGAMENTO_APRAZO
	(
	ID_PLANO
	)
GO
COMMIT
