CREATE TABLE PRODUCAO(
	ID int PRIMARY KEY NOT NULL,
	LOTE int NOT NULL,
	DATA_FABRICACAO datetime NOT NULL,
	ID_PRODUTO numeric(18, 0) NOT NULL,
	QUANTIDADE numeric(18, 3) NOT NULL,
	ID_ESTOQUE int NOT NULL,
	ID_LOJA numeric(18, 0) NOT NULL);
	
ALTER TABLE PRODUCAO WITH NOCHECK ADD CONSTRAINT
	FK_PRODUCAO_PRODUTO FOREIGN KEY
	(
	ID_PRODUTO
	) REFERENCES PRODUTO
	(
	ID
	)

ALTER TABLE PRODUCAO WITH NOCHECK ADD CONSTRAINT
	FK_PRODUCAO_ESTOQUE FOREIGN KEY
	(
	ID_ESTOQUE,
	ID_LOJA
	) REFERENCES ESTOQUE
	(
	ID,
	ID_LOJA
	)