ALTER TABLE CONTA_CORRENTE
ADD DIGITO_CONTA_CORRENTE VARCHAR(1) NULL, CARTEIRA VARCHAR(3) NULL;

ALTER TABLE CONTA_CORRENTE
ADD MSN_BOLETO_1 VARCHAR(100) NULL, MSN_BOLETO_2 VARCHAR(100) NULL, MSN_BOLETO_3 VARCHAR(100) NULL, MSN_BOLETO_4 VARCHAR(100) NULL;