
CREATE TABLE EVENTO_ITEM_PAGAMENTO_BOLETO(
	LOJA int NOT NULL,
	COMPONENTE int NOT NULL,
	NUM_TRANSACAO int NOT NULL,
	DATA_TRANSACAO date NOT NULL,
	NUM_EVENTO int NOT NULL,
PRIMARY KEY  
(
	LOJA ,
	COMPONENTE ,
	NUM_TRANSACAO ,
	DATA_TRANSACAO
) )


GO
USE ENTERPRISE
GO
ALTER TABLE dbo.EVENTO_ITEM_PAGAMENTO_BOLETO  WITH CHECK ADD  CONSTRAINT FKB5E23ADC991B006B FOREIGN KEY(BOLETO)
REFERENCES dbo.BOLETO (ID)