insert into macro_operacao (id,descricao,tipo_componente) values (101,'Saida Sistema Fechado',2);
insert into macro_operacao (id,descricao,tipo_componente) values (102,'Saida Sistema Aberto',2);
insert into macro_operacao (id,descricao,tipo_componente) values (103,'Saida Sistema Devolucao',2);
insert into macro_operacao (id,descricao,tipo_componente) values (104,'Saida Sistema Pedido',2);
insert into macro_operacao (id,descricao,tipo_componente) values (105,'Abertura de AV',2);
insert into macro_operacao (id,descricao,tipo_componente) values (106,'Volta Fechado',2);
insert into macro_operacao (id,descricao,tipo_componente) values (107,'Saida Separacao',2);
insert into macro_operacao (id,descricao,tipo_componente) values (108,'Volta Separacao',2);
insert into macro_operacao (id,descricao,tipo_componente) values (109,'Pedido',2);
insert into macro_operacao (id,descricao,tipo_componente) values (110,'Volta Fechado',2);
insert into macro_operacao (id,descricao,tipo_componente) values (111,'Desconto Item',2);
insert into macro_operacao (id,descricao,tipo_componente) values (112,'Venda Item',2);
insert into macro_operacao (id,descricao,tipo_componente) values (113,'Excluir Venda Item',2);
insert into macro_operacao (id,descricao,tipo_componente) values (114,'Finaliza Pedido',2);
insert into macro_operacao (id,descricao,tipo_componente) values (115,'Finaliza Separacao',2);
insert into macro_operacao (id,descricao,tipo_componente) values (116,'Separacao',2);
insert into macro_operacao (id,descricao,tipo_componente) values (117,'Separa Item',2);
insert into macro_operacao (id,descricao,tipo_componente) values (118,'Cancela Pedido',2);
insert into macro_operacao (id,descricao,tipo_componente) values (119,'Altera Pedido',2);
insert into macro_operacao (id,descricao,tipo_componente) values (120,'Saida Altera Pedido',2);
insert into macro_operacao (id,descricao,tipo_componente) values (121,'Excluir Item Altera Pedido',2);
insert into macro_operacao (id,descricao,tipo_componente) values (122,'Adicionar Item Altera Pedido',2);
insert into macro_operacao (id,descricao,tipo_componente) values (123,'Finalizar Altera Pedido',2);
insert into macro_operacao (id,descricao,tipo_componente) values (124,'Cancelar Altera Pedido',2);
insert into macro_operacao (id,descricao,tipo_componente) values (125,'Desconto Item Altera Pedido',2);

insert into macro_operacao (id,descricao,tipo_componente) values (39,'Solicita Carga Base',1);
insert into macro_operacao (id,descricao,tipo_componente) values (40,'Resgate de Pedido',1);
insert into macro_operacao (id,descricao,tipo_componente) values (41,'Recebimento em Boleto',1);
insert into macro_operacao (id,descricao,tipo_componente) values (42,'Consulta Pedido',1);
insert into macro_operacao (id,descricao,tipo_componente) values (43,'Número do Pedido',1);