package com.infinity.datamarket.pdv.gui.telas.swing;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.rmi.RemoteException;
import java.text.ParseException;
import java.util.Date;

import javax.swing.JDialog;
import javax.swing.JFormattedTextField;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

import com.infinity.datamarket.cliente.ClienteServerRemote;
import com.infinity.datamarket.comum.transacao.ClienteTransacao;
import com.infinity.datamarket.comum.util.AppException;
import com.infinity.datamarket.comum.util.Util;
import com.infinity.datamarket.pdv.gerenciadorperifericos.components.LimitedTextField;
import com.infinity.datamarket.pdv.util.ServerConfig;
import com.infinity.datamarket.pdv.util.ServiceLocator;

public class TelaCadastroClientePDV extends JDialog {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5323773017522689751L;
	public static final int OK = 0;
	public static final int CANCELA = 1;
	
	public static int retorno = CANCELA;
	    
    /** Creates new form TelaCadastroCliente */
    private TelaCadastroClientePDV(JFrame owner) {
        super(owner,true);
    	initComponents();
    }
    
    private void mostrarMensagem(String mensagem){
    	JOptionPane.showMessageDialog(this, mensagem,"Atenção",JOptionPane.INFORMATION_MESSAGE);
    }
    
    private boolean validaCampos(){
    	if (jRadioButtonPessoaFisica.isSelected()){
			if (!Util.validacpf(jTextFieldCpfCnpj.getText())){
				mostrarMensagem("CPF inválido");
				jTextFieldCpfCnpj.requestFocus();
				return false;
			}
		}else if (jRadioButtonPessoaJuridica.isSelected()){
			if (!Util.validaCnpj(jTextFieldCpfCnpj.getText())){
				mostrarMensagem("CNPJ inválido");
				jTextFieldCpfCnpj.requestFocus();
				return false;
			}
		}
		if (jTextFieldNome.getText() == null || jTextFieldNome.getText().length() < 3){						
			mostrarMensagem("Nome deve ter pelo menos 3 caracteres");
			jTextFieldNome.requestFocus();
			return false;
		}
		return true;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">                          
    private void initComponents() {
    	
    	try {
			mascaraCPF = new MaskFormatter("###.###.###-##");
			mascaraCNPJ = new MaskFormatter("##.###.###/####-##");
			
			mascaraCNPJ.setValidCharacters("0123456789");
			mascaraCPF.setValidCharacters("0123456789");
						
			mascaraTelefone = new MaskFormatter("(##)####-####");
			mascaraTelefone.setValidCharacters("0123456789");
			
			
		} catch (ParseException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    	
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldCpfCnpj = new JFormattedTextField(mascaraCPF);
        
        kl = new KeyListener(){
			public void keyPressed(KeyEvent e) {
				if (e.getKeyCode() == e.VK_ENTER){
					if (validaCampos()){
						retorno = OK;
						fechar();
					}
				}else if(e.getKeyCode() == e.VK_ESCAPE){
					retorno = CANCELA;
					fechar();					
				}
			}
			public void keyReleased(KeyEvent e) {
				
			}
			public void keyTyped(KeyEvent e) {
				
			}	
        	
        };
        
        
        
        jRadioButtonPessoaFisica = new javax.swing.JRadioButton();
        jRadioButtonPessoaJuridica = new javax.swing.JRadioButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldTelefone = new JFormattedTextField(mascaraTelefone);
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCelular = new JFormattedTextField(mascaraTelefone);
        jLabel4 = new javax.swing.JLabel();
        jTextFieldInscEstadual = new LimitedTextField(20);
        jLabel5 = new javax.swing.JLabel();
        jTextFieldInscMunicipal = new LimitedTextField(20);
        jLabel6 = new javax.swing.JLabel();
        jTextFieldRazaoSocial = new LimitedTextField(50);
        jTextFieldRazaoSocial.setMascara(jTextFieldNome.ALFANUMERICO);
        jLabel7 = new javax.swing.JLabel();
        jTextFieldContato = new LimitedTextField(20);
        jTextFieldContato.setMascara(jTextFieldNome.ALFANUMERICO);
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaRefBancaria = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldLogradouro = new LimitedTextField(50);
        jTextFieldLogradouro.setMascara(jTextFieldNome.ALFANUMERICO);
        jComboBoxEstado = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldCidade = new LimitedTextField(50);
        jTextFieldCidade.setMascara(jTextFieldNome.ALFANUMERICO);
        jLabel12 = new javax.swing.JLabel();
        jTextFieldCep = new LimitedTextField(8);
        jTextFieldNumero = new LimitedTextField(6);
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldComplemento = new LimitedTextField(50);
        jTextFieldComplemento.setMascara(jTextFieldNome.ALFANUMERICO);
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldNome = new LimitedTextField(50);
        jTextFieldNome.setMascara(jTextFieldNome.ALFANUMERICO);
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        
        jLabel1.setText("jLabel1");
        jLabel8.setText("jLabel8");
        jLabel15.setText("jLabel15");

        getContentPane().setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        
        setResizable(false);
        jPanel2.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("CPF/CNPJ"));
        jPanel2.add(jTextFieldCpfCnpj);
        jTextFieldCpfCnpj.setBounds(180, 20, 150, 20);

        jRadioButtonPessoaFisica.setText("F\u00edsica");
        jRadioButtonPessoaFisica.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButtonPessoaFisica.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jPanel2.add(jRadioButtonPessoaFisica);
        jRadioButtonPessoaFisica.setBounds(20, 20, 60, 15);

        jRadioButtonPessoaJuridica.setText("Jur\u00eddica");
        jRadioButtonPessoaJuridica.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButtonPessoaJuridica.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jPanel2.add(jRadioButtonPessoaJuridica);
        jRadioButtonPessoaJuridica.setBounds(80, 20, 65, 15);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 0, 340, 50);

        jPanel3.setLayout(null);

        jLabel2.setText("Telefone");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(10, 110, 50, 14);

        jPanel3.add(jTextFieldTelefone);
        jTextFieldTelefone.setBounds(10, 130, 85, 20);

        jLabel3.setText("Celular");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(105, 110, 45, 14);

        jPanel3.add(jTextFieldCelular);
        jTextFieldCelular.setBounds(105, 130, 85, 20);

        jLabel4.setText("Inscri\u00e7\u00e3o Estadual");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(10, 60, 120, 15);

        jPanel3.add(jTextFieldInscEstadual);
        jTextFieldInscEstadual.setBounds(10, 80, 155, 20);

        jLabel5.setText("Inscri\u00e7\u00e3o Munincipal");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(175, 60, 150, 15);

        jPanel3.add(jTextFieldInscMunicipal);
        jTextFieldInscMunicipal.setBounds(175, 80, 155, 20);

        jLabel6.setText("Razão Social");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(10, 10, 90, 14);

        jPanel3.add(jTextFieldRazaoSocial);
        jTextFieldRazaoSocial.setBounds(10, 30, 320, 20);

        jLabel7.setText("Contato");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(200, 110, 70, 14);

        jPanel3.add(jTextFieldContato);
        jTextFieldContato.setBounds(200, 130, 130, 20);

        jLabel16.setText("Refer\u00eancia Banc\u00e1ria");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(10, 160, 120, 14);

        jTextAreaRefBancaria.setColumns(20);
        jTextAreaRefBancaria.setRows(5);
        jScrollPane1.setViewportView(jTextAreaRefBancaria);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(10, 180, 320, 50);

        jTabbedPane1.addTab("Dados Gerais", jPanel3);

        jPanel4.setLayout(null);

        jLabel9.setText("Logradouro");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(10, 60, 70, 14);

        jPanel4.add(jTextFieldLogradouro);
        jTextFieldLogradouro.setBounds(10, 80, 310, 20);

        jComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC","AL","AM","AP","BA","CE","DF","ES","GO","MA","MG","MS","MT","PA","PB","PE","PI","PR","RJ","RN","RO","RR","RS","SC","SE","SP","TO" }));
        jPanel4.add(jComboBoxEstado);
        jComboBoxEstado.setBounds(10, 130, 50, 20);

        jLabel11.setText("Cidade");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(70, 110, 50, 14);

        jPanel4.add(jTextFieldCidade);
        jTextFieldCidade.setBounds(70, 130, 250, 20);

        jLabel12.setText("Cep");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(10, 10, 25, 14);

        jPanel4.add(jTextFieldCep);
        jTextFieldCep.setBounds(10, 30, 70, 20);

        jPanel4.add(jTextFieldNumero);
        jTextFieldNumero.setBounds(10, 180, 50, 20);

        jLabel13.setText("N\u00famero");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(10, 160, 80, 14);

        jLabel14.setText("Complemento");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(70, 160, 90, 14);

        jPanel4.add(jTextFieldComplemento);
        jTextFieldComplemento.setBounds(70, 180, 250, 20);

        jLabel10.setText("UF");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(10, 110, 40, 14);

        jTabbedPane1.addTab("Endere\u00e7o", jPanel4);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(10, 110, 340, 270);
        jTabbedPane1.getAccessibleContext().setAccessibleName("tab2");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome"));
        
        jPanel1.setLayout(null);
        jPanel1.add(jTextFieldNome);
        jTextFieldNome.setBounds(10, 20, 320, 20);
        
        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 50, 340, 50);

        jButton1.setText("OK");
        getContentPane().add(jButton1);
        jButton1.setBounds(260, 390, 90, 23);

        jButton2.setText("Cancelar");
        getContentPane().add(jButton2);
        jButton2.setBounds(160, 390, 90, 23);

        jRadioButtonPessoaFisica.setSelected(true);
        jTextFieldInscEstadual.setEnabled(false);
		jTextFieldInscMunicipal.setEnabled(false);
		jTextFieldRazaoSocial.setEnabled(false);
        
        buttonGroup1.add(jRadioButtonPessoaFisica);
        buttonGroup1.add(jRadioButtonPessoaJuridica);
        
        jRadioButtonPessoaFisica.addActionListener(new ActionListener(){

			public void actionPerformed(ActionEvent e) {
				clickRadio();
				
			}

			
        	
        });
        
        jRadioButtonPessoaJuridica.addActionListener(new ActionListener(){

			public void actionPerformed(ActionEvent e) {
				clickRadio();
				
			}

			
        	
        });
        
        jButton2.addActionListener(new ActionListener(){

			public void actionPerformed(ActionEvent e) {
				retorno = CANCELA;
				fechar();
				
				
			}

			
        	
        });
        
        jButton1.addActionListener(new ActionListener(){

			public void actionPerformed(ActionEvent e) {
				if (validaCampos()){
					retorno = OK;
					fechar();
				}
			}

			
        	
        });

        
        jTextFieldCpfCnpj.addKeyListener(new KeyListener(){

			public void keyPressed(KeyEvent e) {
				if (e.getKeyCode() == e.VK_ENTER){
					try{
						ClienteServerRemote remote = (ClienteServerRemote) ServiceLocator.getJNDIObject(ServerConfig.CLIENTE_SERVER_JNDI);
						String cpfCnpj = jTextFieldCpfCnpj.getText().replace(".", "");
				    	cpfCnpj = cpfCnpj.replace("/", "");
				    	cpfCnpj = cpfCnpj.replace("-", "");
						ClienteTransacao cliente = remote.consultarClienteTransacaoPorID(cpfCnpj);
						
					
					}catch(AppException ex){
						mostrarMensagem("Cliente não Encontrado");
					}catch(Exception ex){
						mostrarMensagem("Erro de Comunicação");
					}	
				}
			}

			public void keyReleased(KeyEvent e) {
				// TODO Auto-generated method stub
				
			}

			public void keyTyped(KeyEvent e) {
				// TODO Auto-generated method stub
				
			}
        	
        });
        
        
        jTextFieldNome.addKeyListener(kl);
        jTextFieldTelefone.addKeyListener(kl);
        jTextFieldCelular.addKeyListener(kl);
        jTextFieldInscEstadual.addKeyListener(kl);
        jTextFieldInscMunicipal.addKeyListener(kl);
        jTextFieldRazaoSocial.addKeyListener(kl);
        jTextFieldContato.addKeyListener(kl);
        jTextFieldLogradouro.addKeyListener(kl);
        jTextFieldCidade.addKeyListener(kl);
        jTextFieldCep.addKeyListener(kl);
        jTextFieldNumero.addKeyListener(kl);
        jTextFieldComplemento.addKeyListener(kl);
        jTextAreaRefBancaria.addKeyListener(kl);
        jRadioButtonPessoaFisica.addKeyListener(kl);
        jRadioButtonPessoaJuridica.addKeyListener(kl);
        jTabbedPane1.addKeyListener(kl);
        jButton1.addKeyListener(kl);
        jButton2.addKeyListener(kl);
        
        

        
    }// </editor-fold>    
    
    private void fechar(){
    	this.setVisible(false);
    }
    
    private void clickRadio(){
    	jPanel2.remove(jTextFieldCpfCnpj);
    	if (jRadioButtonPessoaFisica.isSelected()){
    		jTextFieldCpfCnpj = new JFormattedTextField(mascaraCPF);
    		jTextFieldInscEstadual.setText("");
    		jTextFieldInscEstadual.setEnabled(false);
    		jTextFieldInscMunicipal.setText("");
    		jTextFieldInscMunicipal.setEnabled(false);
    		jTextFieldRazaoSocial.setText("");
    		jTextFieldRazaoSocial.setEnabled(false);
    	}else{
    		jTextFieldInscEstadual.setText("");
    		jTextFieldInscEstadual.setEnabled(true);
    		jTextFieldInscMunicipal.setText("");
    		jTextFieldInscMunicipal.setEnabled(true);
    		jTextFieldRazaoSocial.setText("");
    		jTextFieldRazaoSocial.setEnabled(true);
    		jTextFieldCpfCnpj = new JFormattedTextField(mascaraCNPJ);    		
    	}
    	jPanel2.add(jTextFieldCpfCnpj);
    	jTextFieldCpfCnpj.setBounds(180, 20, 150, 20);
    	jPanel2.repaint();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {            	
//                if (TelaCadastroClientePDV.iniciar(new JFrame()) == TelaCadastroClientePDV.OK){
//                	System.out.println("OK");
//                }else{
//                	System.out.println("CANCELA");
//                }
//               
            }
        });
    }
    
    public ClienteTransacao getClienteTransacao(){
    	ClienteTransacao c = new ClienteTransacao();
    	String cpfCnpj = jTextFieldCpfCnpj.getText().replace(".", "");
    	cpfCnpj = cpfCnpj.replace("/", "");
    	cpfCnpj = cpfCnpj.replace("-", "");
    	c.setCpfCnpj(cpfCnpj);
//    	c.setBairro(jt)
    	String celular = jTextFieldTelefone.getText().replace("-", "");
    	celular = celular.replace(" ", "");
    	celular = celular.replace("(", "");
    	celular = celular.replace(")", "");
    	c.setCelular(celular);
    	c.setCep(jTextFieldCep.getText());
    	c.setCidade(jTextFieldCidade.getText());
    	c.setComplemento(jTextFieldComplemento.getText());
    	c.setDataCadastro(new Date());
//    	c.setEmail(email)
    	c.setEstado(jComboBoxEstado.getSelectedItem().toString());
    	String telefone = jTextFieldTelefone.getText().replace("-", "");
    	telefone = telefone.replace(" ", "");
    	telefone = telefone.replace("(", "");
    	telefone = telefone.replace(")", "");
    	c.setFone(telefone);
    	c.setInscricaoEstadual(jTextFieldInscEstadual.getText());
    	c.setInscricaoMunicipal(jTextFieldInscMunicipal.getText());
    	c.setLogradouro(jTextFieldLogradouro.getText());
    	c.setNomeCliente(jTextFieldNome.getText());
    	c.setNumero(jTextFieldNumero.getText());
    	c.setPessoaContato(jTextFieldContato.getText());
    	c.setRazaoSocial(jTextFieldRazaoSocial.getText());
    	c.setReferenciaBancaria(jTextAreaRefBancaria.getText());
    	c.setTipoPessoa(jRadioButtonPessoaFisica.isSelected()?c.PESSOA_FISICA:c.PESSOA_JURIDICA);
    	return c;
    }
    
    public static TelaCadastroClientePDV iniciar(JFrame owner){
    	TelaCadastroClientePDV tela = new TelaCadastroClientePDV(owner);
    	tela.setSize(370, 460);
        tela.setVisible(true);
    	return tela;
	}
    private transient KeyListener kl;    
    // Variables declaration - do not modify                     
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBoxEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButtonPessoaFisica;
    private javax.swing.JRadioButton jRadioButtonPessoaJuridica;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextAreaRefBancaria;
    private JFormattedTextField jTextFieldCpfCnpj;
    private LimitedTextField jTextFieldCidade;
    private LimitedTextField jTextFieldCep;
    private LimitedTextField jTextFieldNumero;
    private LimitedTextField jTextFieldComplemento;
    private LimitedTextField jTextFieldNome;
    private JFormattedTextField jTextFieldTelefone;
    private JFormattedTextField jTextFieldCelular;
    private LimitedTextField jTextFieldInscEstadual;
    private LimitedTextField jTextFieldInscMunicipal;
    private LimitedTextField jTextFieldRazaoSocial;
    private LimitedTextField jTextFieldContato;
    private LimitedTextField jTextFieldLogradouro;

	
	private MaskFormatter mascaraCPF;
	private MaskFormatter mascaraCNPJ;
	private MaskFormatter mascaraTelefone;
	
}
