USE [PDV]
GO
/****** Object:  Table [dbo].[FUNCIONALIDADE]    Script Date: 03/04/2008 19:37:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[FUNCIONALIDADE](
	[ID] [int] NOT NULL,
	[ID_FUNC_SUPERIOR] [int] NULL,
	[DESCRICAO] [varchar](50) NOT NULL,
	[SITUACAO] [varchar](1) NOT NULL,
	[URL] [varchar](1000) NULL,
 CONSTRAINT [PK_Table_1] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[FUNCIONALIDADE]  WITH CHECK ADD  CONSTRAINT [FK_FUNC_SUP_FUNCIONALIDADE] FOREIGN KEY([ID_FUNC_SUPERIOR])
REFERENCES [dbo].[FUNCIONALIDADE] ([ID])
GO
ALTER TABLE [dbo].[FUNCIONALIDADE] CHECK CONSTRAINT [FK_FUNC_SUP_FUNCIONALIDADE]
GO
ALTER TABLE [dbo].[FUNCIONALIDADE]  WITH CHECK ADD  CONSTRAINT [FK_FUNCIONALIDADE_FUNCIONALIDADE] FOREIGN KEY([ID])
REFERENCES [dbo].[FUNCIONALIDADE] ([ID])
GO
ALTER TABLE [dbo].[FUNCIONALIDADE] CHECK CONSTRAINT [FK_FUNCIONALIDADE_FUNCIONALIDADE]