CREATE TABLE [dbo].[AJUSTE_ESTOQUE] (
	[ID_ESTOQUE] [int] NULL ,
	[ID_LOJA] [numeric](18, 0) NULL ,
	[DATA] [datetime] NULL ,
	[ID] [int] NOT NULL ,
	[ID_PRODUTO] [numeric](18, 0) NULL ,
	[QTD_ANTES] [numeric](18, 3) NULL ,
	[QTD_DEPOIS] [numeric](18, 3) NULL ,
	[COD_USUARIO] [int] NULL 
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[AJUSTE_ESTOQUE] ADD 
	CONSTRAINT [PK_AJUSTE_ESTOQUE] PRIMARY KEY  CLUSTERED 
	(
		[ID]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[AJUSTE_ESTOQUE] ADD 
	CONSTRAINT [FK_AJUSTE_ESTOQUE_ESTOQUE] FOREIGN KEY 
	(
		[ID_ESTOQUE],
		[ID_LOJA]
	) REFERENCES [dbo].[ESTOQUE] (
		[ID],
		[ID_LOJA]
	),
	CONSTRAINT [FK_AJUSTE_ESTOQUE_PRODTO] FOREIGN KEY 
	(
		[ID_PRODUTO]
	) REFERENCES [dbo].[PRODUTO] (
		[ID]
	)
GO

