/*
   quarta-feira, 11 de junho de 2008 21:42:46
   User: 
   Server: (local)
   Database: PDV
   Application: MS SQLEM - Data Tools
*/

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.FUNCIONALIDADE ADD
	LARGURA int NULL,
	ALTURA int NULL
GO
ALTER TABLE dbo.FUNCIONALIDADE ADD CONSTRAINT
	DF_FUNCIONALIDADE_LARGURA DEFAULT 800 FOR LARGURA
GO
ALTER TABLE dbo.FUNCIONALIDADE ADD CONSTRAINT
	DF_FUNCIONALIDADE_ALTURA DEFAULT 600 FOR ALTURA
GO
COMMIT
