/*
   terça-feira, 9 de setembro de 2008 21:46:09
   User: 
   Server: (local)
   Database: ENTERPRISE
   Application: MS SQLEM - Data Tools
*/

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.CLIENTE_PAGTO ADD
	ID_USUARIO int NOT NULL
GO
ALTER TABLE dbo.CLIENTE_PAGTO WITH NOCHECK ADD CONSTRAINT
	FK_CLIENTE_PAGTO_USUARIO FOREIGN KEY
	(
	ID_USUARIO
	) REFERENCES dbo.USUARIO
	(
	ID
	)
GO
COMMIT
