/*
   segunda-feira, 10 de novembro de 2008 11:34:30
   User: 
   Server: (local)
   Database: PDV
   Application: MS SQLEM - Data Tools
*/

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.ENTRADA_PRODUTO ADD
	STATUS varchar(1) NOT NULL CONSTRAINT DF_ENTRADA_PRODUTO_STATUS DEFAULT 'A'
GO
COMMIT
