CREATE TABLE [dbo].[MOVIMENTACAO_BANCARIA] (
  [ID] int NOT NULL,
  [ID_CONTA] int NOT NULL,
  [TIPO] int NULL,
  [NUMERO] varchar(20) COLLATE Latin1_General_CI_AI NULL,
  [DATA] datetime NULL,
  [VALOR] numeric(18, 2) NULL,
  [ID_FORMA] numeric(18, 0) NULL,
  PRIMARY KEY CLUSTERED ([ID], [ID_CONTA]),
  CONSTRAINT [FK_MOVIMENTACAO_BANCARIA_CONTA] FOREIGN KEY ([ID_CONTA]) 
  REFERENCES [dbo].[CONTA_CORRENTE] ([ID]) 
  ON UPDATE NO ACTION
  ON DELETE NO ACTION,
  CONSTRAINT [FK_MOVIMENTACAO_BANCARIA_FORMA] FOREIGN KEY ([ID_FORMA]) 
  REFERENCES [dbo].[FORMA_RECEBIMENTO] ([ID]) 
  ON UPDATE NO ACTION
  ON DELETE NO ACTION
)
ON [PRIMARY]
GO