/*
   sábado, 6 de junho de 2009 10:45:43
   User: 
   Server: (local)
   Database: ENTERPRISE
   Application: MS SQLEM - Data Tools
*/

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.CONTA_CORRENTE ADD
	ID_LOJA numeric(18, 0)
GO
ALTER TABLE dbo.CONTA_CORRENTE ADD CONSTRAINT
	FK_CONTA_CORRENTE_LOJA FOREIGN KEY
	(
	ID_LOJA
	) REFERENCES dbo.LOJA
	(
	ID
	)
GO
COMMIT
