/*
   terça-feira, 4 de agosto de 2009 22:06:34
   User: 
   Server: (local)
   Database: ENTERPRISE
   Application: MS SQLEM - Data Tools
*/

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.LANCAMENTO ADD
	ID_CLIENTE int NULL
GO
COMMIT
