CREATE TABLE BOLETO(
	ID bigint NOT NULL,
	COMPONENTE int NULL,
	USUARIO int NULL,
	CLIENTE int NULL,
	LOJA int NOT NULL,
	STATUS int NOT NULL,
	CONTA_CORRENTE bigint NOT NULL,
	CEDENTE varchar(35)  NOT NULL,
	NOSSO_NUMERO varchar(8)  NOT NULL,
	AGENCIA varchar(4)  NOT NULL,
	CARTEIRA varchar(3)  NOT NULL,
	NUMERO_CONTA_CORRENTE varchar(5)  NOT NULL,
	DIGITO_CONTA_CORRENTE varchar(1)  NOT NULL,
	VALOR decimal NOT NULL,
	INSTRUCAO1 varchar(100)  NULL,
	INSTRUCAO2 varchar(100)  NULL,
	INSTRUCAO3 varchar(100)  NULL,
	INSTRUCAO4 varchar(100)  NULL,
	TIPO_BANCO int NOT NULL,
	DATA_vencimento datetime NOT NULL,
	DATA_PROCESSAMENTO datetime NOT NULL,
	NOME_CLIENTE varchar(100)  NULL,
	ENDERECO_CLIENTE varchar(100) NULL,
	BAIRRO_CLIENTE varchar(100) NULL,
	CIDADE_CLIENTE varchar(100) NULL,
	UF_CLIENTE varchar(100)  NULL,
	CPF_CNPJ varchar(100) NULL,
	CEP_CLIENTE varchar(100) NULL,
PRIMARY KEY  
(
	ID 
))




