USE [ENTERPRISE]
GO
/****** Object:  Table [dbo].[EVENTO_ITEM_PAGAMENTO_BOLETO]    Script Date: 11/03/2009 22:52:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EVENTO_ITEM_PAGAMENTO_BOLETO](
	[LOJA] [int] NOT NULL,
	[COMPONENTE] [int] NOT NULL,
	[NUM_TRANSACAO] [int] NOT NULL,
	[DATA_TRANSACAO] [datetime] NOT NULL,
	[NUM_EVENTO] [int] NOT NULL,
	[BOLETO] [numeric](19, 0) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[LOJA] ASC,
	[COMPONENTE] ASC,
	[NUM_TRANSACAO] ASC,
	[DATA_TRANSACAO] ASC,
	[NUM_EVENTO] ASC
)WITH (IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
USE [ENTERPRISE]
GO
ALTER TABLE [dbo].[EVENTO_ITEM_PAGAMENTO_BOLETO]  WITH CHECK ADD  CONSTRAINT [FKB5E23ADC991B006B] FOREIGN KEY([BOLETO])
REFERENCES [dbo].[BOLETO] ([ID])