USE [ENTERPRISE]
GO
/****** Object:  Table [dbo].[ARQUIVO_PROCESSADO]    Script Date: 11/03/2009 22:53:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ARQUIVO_PROCESSADO](
	[ID] [numeric](19, 0) NOT NULL,
	[NOME_ARQUIVO] [varchar](255) COLLATE Latin1_General_CI_AI NOT NULL,
	[DATA_HORA_INICIAL] [datetime] NOT NULL,
	[DATA_HORA_FINAL] [datetime] NULL,
	[DATA_PROCESSAMENTO] [datetime] NOT NULL,
	[ID_BANCO] [numeric](19, 0) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF