/****** Object:  Table [dbo].[BOLE_EVEN_ITEM_TRANS_BOLE]    Script Date: 11/14/2009 16:39:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BOLE_EVEN_ITEM_TRANS_BOLE](
	[LOJA] [int] NOT NULL,
	[COMPONENTE] [int] NOT NULL,
	[NUM_TRANSACAO] [int] NOT NULL,
	[DATA_TRANSACAO] [datetime] NOT NULL,
	[NUM_EVENTO] [int] NOT NULL,
	[BOLETO] [numeric](19, 0) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[LOJA] ASC,
	[COMPONENTE] ASC,
	[NUM_TRANSACAO] ASC,
	[DATA_TRANSACAO] ASC,
	[NUM_EVENTO] ASC,
	[BOLETO] ASC
)WITH (IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[BOLE_EVEN_ITEM_TRANS_BOLE]  WITH CHECK ADD  CONSTRAINT [FK_BOLE_EVEN_ITEM_TRANS_BOLE] FOREIGN KEY([BOLETO])
REFERENCES [dbo].[BOLETO] ([ID])
GO
ALTER TABLE [dbo].[BOLE_EVEN_ITEM_TRANS_BOLE]  WITH CHECK ADD  CONSTRAINT [FK_TRAN_EVEN_ITEM_TRANS_BOLE] FOREIGN KEY([LOJA], [COMPONENTE], [NUM_TRANSACAO], [DATA_TRANSACAO], [NUM_EVENTO])
REFERENCES [dbo].[EVENTO_ITEM_PAGAMENTO_BOLETO] ([LOJA], [COMPONENTE], [NUM_TRANSACAO], [DATA_TRANSACAO], [NUM_EVENTO])
GO