/*
   quinta-feira, 12 de novembro de 2009 18:30:58
   User: 
   Server: (local)
   Database: ENTERPRISE_PRD
   Application: MS SQLEM - Data Tools
*/

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.AJUSTE_ESTOQUE ADD
	DATA_OPERACAO datetime NOT NULL,
	USUARIO int NOT NULL
GO
COMMIT
