CREATE TABLE CONTA_CORRENTE(
	ID int NOT NULL,
	AGENCIA varchar(10)  NOT NULL,
	NUMERO varchar(10)  NOT NULL,
	NOME varchar(20)  NOT NULL,
	SALDO decimal NOT NULL,
	SITUACAO varchar(1)  NULL,
	ID_BANCO int NULL,
	ID_LOJA bigint NULL,
	DIGITO_CONTA_CORRENTE varchar(1) NULL,
	CARTEIRA varchar(3)  NULL,
	MSN_BOLETO_1 varchar(100)  NULL,
	MSN_BOLETO_2 varchar(100)  NULL,
	MSN_BOLETO_3 varchar(100)  NULL,
	MSN_BOLETO_4 varchar(100)  NULL,
PRIMARY KEY  
(
	ID 
)
) 





GO
SET ANSI_PADDING OFF
GO
USE ENTERPRISE
GO
ALTER TABLE dbo.CONTA_CORRENTE  WITH CHECK ADD  CONSTRAINT FK_CONTA_BANCO FOREIGN KEY(ID_BANCO)
REFERENCES dbo.BANCO (ID)
GO
ALTER TABLE dbo.CONTA_CORRENTE  WITH CHECK ADD  CONSTRAINT FK_CONTA_CORRENTE_LOJA FOREIGN KEY(ID_LOJA)
REFERENCES dbo.LOJA (ID)
GO
ALTER TABLE dbo.CONTA_CORRENTE  WITH CHECK ADD  CONSTRAINT FKA3D3976AD42C77B FOREIGN KEY(ID_BANCO)
REFERENCES dbo.BANCO (ID)
GO
ALTER TABLE dbo.CONTA_CORRENTE  WITH CHECK ADD  CONSTRAINT FKA3D3976EDB68DBC FOREIGN KEY(ID_LOJA)
REFERENCES dbo.LOJA (ID)