CREATE TABLE  PRODUTO_COMPOSICAO(
	ID_PRODUTO_COMPOSICAO bigint NOT NULL,
	ID_PRODUTO bigint NOT NULL,
	QUANTIDADE decimal NULL,
	ID bigint NULL,
PRIMARY KEY  
(
	ID_PRODUTO_COMPOSICAO ,
	ID_PRODUTO 
)
)