ALTER TABLE OPERACAO_PEDIDO ADD
	ENDERECO_ENTREGA varchar(1) NULL,
	LOGRADOURO varchar(200) NULL,
	NUMERO varchar(20) NULL,
	COMPLEMENTO varchar(50) NULL,
	BAIRRO varchar(50) NULL,
	CIDADE varchar(50) NULL,
	ESTADO varchar(2) NULL,
	CEP varchar(10) NULL,
	PONTO_REFERENCIA varchar(200) NULL
