/****** Object:  Table [dbo].[EVEN_ITEM_TRANS_CARTAO]    Script Date: 11/14/2009 16:39:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EVEN_ITEM_TRANS_CARTAO](
	[LOJA] [numeric](18, 0) NOT NULL,
	[COMPONENTE] [numeric](18, 0) NOT NULL,
	[NUM_TRANSACAO] [numeric](18, 0) NOT NULL,
	[DATA_TRANSACAO] [datetime] NOT NULL,
	[NUM_EVENTO] [numeric](18, 0) NOT NULL,
	[IDENTIFICACAO] [numeric](19, 0) NOT NULL,
	[DOC_FISCAL_COO] [numeric](19, 0) NULL,
	[VALOR] [numeric](19, 2) NOT NULL,
	[MOEDA] [int] NOT NULL,
	[STATUS] [int] NOT NULL,
	[REDE] [varchar](100) COLLATE Latin1_General_CI_AI NULL,
	[TIPO_TRANSACAO] [int] NOT NULL,
	[NUMERO_TRANSACAO_NSU] [numeric](19, 0) NOT NULL,
	[CODIGO_AUTORIZACAO] [int] NULL,
	[NUMERO_LOTE_TRANSACAO] [numeric](19, 0) NOT NULL,
	[DATA_HORA_TRANSACAO_HOST] [datetime] NULL,
	[DATA_HORA_TRANSACAO_LOCAL] [datetime] NULL,
	[TIPO_PARCELAMENTO] [int] NULL,
	[QUANTIDADE_PARCELAMENTO] [int] NULL,
	[DATA_HORA_TRANSACAO] [datetime] NULL,
	[DATA_CARTAO_PRE_DATATADO] [datetime] NULL,
	[CHAVE_FINALIZACAO] [varchar](100) COLLATE Latin1_General_CI_AI NULL,
	[NOME_ADMINISTRADOR] [varchar](100) COLLATE Latin1_General_CI_AI NULL,



 CONSTRAINT [PK_EVEN_ITEM_TRANS_CARTAO] PRIMARY KEY CLUSTERED 
(
	[LOJA] ASC,
	[COMPONENTE] ASC,
	[NUM_TRANSACAO] ASC,
	[DATA_TRANSACAO] ASC,
	[NUM_EVENTO] ASC

)WITH (IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[EVEN_ITEM_TRANS_CARTAO]  WITH CHECK ADD  CONSTRAINT [FK_EVEN_ITEM_TRANS_CARTAO] FOREIGN KEY([LOJA], [COMPONENTE], [NUM_TRANSACAO], [DATA_TRANSACAO], [NUM_EVENTO])
REFERENCES [dbo].[EVENTO_ITEM_PAGAMENTO] ([LOJA], [COMPONENTE], [NUM_TRANSACAO], [DATA_TRANSACAO], [NUM_EVENTO])
GO











/****** Object:  Table [dbo].[PARC_EVE_ITEM_PAG_CHEQUE_PRE]    Script Date: 09/19/2010 11:09:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PARC_EVE_ITEM_PAG_CARTAO](
	[LOJA] [numeric](18, 0) NOT NULL,
	[COMPONENTE] [numeric](18, 0) NOT NULL,
	[NUM_TRANSACAO] [numeric](18, 0) NOT NULL,
	[DATA_TRANSACAO] [datetime] NOT NULL,
	[NUM_EVENTO] [numeric](18, 0) NOT NULL,
	[NSU_PARCELA] [numeric](18, 0) NOT NULL,
	[VALOR] [numeric](18, 2) NULL,
	[DATA] [datetime] NULL,

 CONSTRAINT [PK_PARC_EVE_ITEM_PAG_CARTAO] PRIMARY KEY CLUSTERED 
(
	[LOJA] ASC,
	[COMPONENTE] ASC,
	[NUM_TRANSACAO] ASC,
	[DATA_TRANSACAO] ASC,
	[NUM_EVENTO] ASC,
	[NSU_PARCELA] ASC
)WITH (IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[PARC_EVE_ITEM_PAG_CARTAO]  WITH CHECK ADD  CONSTRAINT [FK_PARC_EVE_ITEM_PAG_CARTAO] FOREIGN KEY([LOJA], [COMPONENTE], [NUM_TRANSACAO], [DATA_TRANSACAO], [NUM_EVENTO])
REFERENCES [dbo].[EVEN_ITEM_TRANS_CARTAO] ([LOJA], [COMPONENTE], [NUM_TRANSACAO], [DATA_TRANSACAO], [NUM_EVENTO])
GO

