delete from perfil_funcionalidade

delete from funcionalidade

insert into funcionalidade values (100, NULL, 'Cadastros'                           , 'S', NULL                                                      ,   0,   0)
insert into funcionalidade values (101,  100, 'Usuário'                             , 'S', NULL                                                      ,   0,   0)
insert into funcionalidade values (102,  101, 'Inserir Usuário'                     , 'S', 'usuario/inserirUsuario'                                  , 800, 500)
insert into funcionalidade values (103,  101, 'Manter Usuário'                      , 'S', 'usuario/consultarUsuario'                                , 800, 500)
insert into funcionalidade values (104,  100, 'Perfil'                              , 'S', NULL                                                      ,   0,   0)
insert into funcionalidade values (105,  104, 'Inserir Perfil'                      , 'S', 'perfil/inserirPerfil'                                    , 800, 500)
insert into funcionalidade values (106,  104, 'Manter Perfil'                       , 'S', 'perfil/consultarPerfil'                                  , 800, 500)
insert into funcionalidade values (107,  100, 'Loja'                                , 'S', NULL                                                      ,   0,   0)
insert into funcionalidade values (108,  107, 'Inserir Loja'                        , 'S', 'loja/inserirLoja'                                        , 800, 500)
insert into funcionalidade values (109,  107, 'Manter Loja'                         , 'S', 'loja/consultarLoja'                                      , 800, 500)
insert into funcionalidade values (110,  100, 'Estoque'                             , 'S', NULL                                                      ,   0,   0)
insert into funcionalidade values (111,  110, 'Inserir Estoque'                     , 'S', 'estoque/inserirEstoque'                                  , 800, 600)
insert into funcionalidade values (112,  110, 'Manter Estoque'                      , 'S', 'estoque/consultarEstoque'                                , 800, 600)
insert into funcionalidade values (113,  100, 'Componente'                          , 'S', NULL                                                      ,   0,   0)
insert into funcionalidade values (114,  113, 'Inserir Componente'                  , 'S', 'componente/inserirComponente'                            , 800, 450)
insert into funcionalidade values (115,  113, 'Manter Componente'                   , 'S', 'componente/consultarComponente'                          , 800, 450)
insert into funcionalidade values (116,  100, 'Administração de Produtos'           , 'S', NULL                                                      ,   0,   0)
insert into funcionalidade values (117,  116, 'Grupo de Produto'                    , 'S', NULL                                                      ,   0,   0)
insert into funcionalidade values (118,  117, 'Inserir Grupo Produto'               , 'S', 'grupoProduto/inserirGrupoProduto'                        , 800, 600)
insert into funcionalidade values (119,  117, 'Manter Grupo de Produto'             , 'S', 'grupoProduto/consultarGrupoProduto'                      , 800, 600)
insert into funcionalidade values (120,  116, 'Tipo de Produto'                     , 'S', NULL                                                      ,   0,   0)
insert into funcionalidade values (121,  120, 'Inserir Tipo de Produto'             , 'S', 'tipoProduto/inserirTipoProduto'                          , 800, 600)
insert into funcionalidade values (122,  120, 'Manter Tipo de Produto'              , 'S', 'tipoProduto/consultarTipoProduto'                        , 800, 600)
insert into funcionalidade values (123,  116, 'Unidade'                             , 'S', NULL                                                      ,   0,   0)
insert into funcionalidade values (124,  123, 'Inserir Unidade'                     , 'S', 'unidade/inserirUnidade'                                  , 800, 600)
insert into funcionalidade values (125,  123, 'Manter Unidade'                      , 'S', 'unidade/consultarUnidade'                                , 800, 600)
insert into funcionalidade values (126,  116, 'Imposto'                             , 'S', NULL                                                      ,   0,   0)
insert into funcionalidade values (127,  126, 'Inserir Imposto'                     , 'S', 'imposto/inserirImposto'                                  , 800, 600)
insert into funcionalidade values (128,  126, 'Manter Imposto'                      , 'S', 'imposto/consultarImposto'                                , 800, 600)
insert into funcionalidade values (129,  116, 'Produto'                             , 'S', NULL                                                      ,   0,   0)
insert into funcionalidade values (130,  129, 'Inserir Produto'                     , 'S', 'produto/inserirProduto'                                  , 550, 600)
insert into funcionalidade values (131,  129, 'Manter Produto'                      , 'S', 'produto/consultarProduto'                                , 800, 600)
insert into funcionalidade values (132,  100, 'Forma de Recebimento'                , 'S', NULL                                                      ,   0,   0)
insert into funcionalidade values (133,  132, 'Inserir Forma de Recebimento'        , 'S', 'formaRecebimento/inserirFormaRecebimento'                , 800, 600)
insert into funcionalidade values (134,  132, 'Manter Forma de Recebimento'         , 'S', 'formaRecebimento/consultarFormaRecebimento'              , 800, 600)
insert into funcionalidade values (135,  100, 'Planos de Pagamento'                 , 'S', NULL                                                      ,   0,   0)
insert into funcionalidade values (153,  135, 'Plano à Vista'                       , 'S', NULL                                                      ,   0,   0)
insert into funcionalidade values (136,  153, 'Inserir Plano'                       , 'S', 'planoPagamento/inserirPlanoPagamento'                    , 800, 600)
insert into funcionalidade values (137,  153, 'Manter Plano'                        , 'S', 'planoPagamento/consultarPlanoPagamento'                  , 800, 600)
insert into funcionalidade values (138,  135, 'Plano à Prazo'                       , 'S', NULL                                                      ,   0,   0)
insert into funcionalidade values (139,  138, 'Inserir Plano'                       , 'S', 'planoPagamentoAPrazo/inserirPlanoPagamentoAPrazo'        , 800, 600)
insert into funcionalidade values (140,  138, 'Manter Plano'                        , 'S', 'planoPagamentoAPrazo/consultarPlanoPagamentoAPrazo'      , 800, 600)
insert into funcionalidade values (141,  100, 'Clientes'                            , 'S', NULL                                                      ,   0,   0)
insert into funcionalidade values (142,  141, 'Inserir Cliente'                     , 'S', 'cliente/inserirCliente'                                  , 800, 600)
insert into funcionalidade values (143,  141, 'Manter Cliente'                      , 'S', 'cliente/consultarCliente'                                , 800, 600)
insert into funcionalidade values (144,  100, 'Autorizadora'                        , 'S', NULL                                                      ,   0,   0)
insert into funcionalidade values (145,  144, 'Inserir Autorizadora'                , 'S', 'autorizadora/inserirAutorizadora'                        , 800, 600)
insert into funcionalidade values (146,  144, 'Consultar Autorizadora'              , 'S', 'autorizadora/consultarAutorizadora'                      , 800, 600)
insert into funcionalidade values (147,  100, 'Fornecedores'                        , 'S', NULL                                                      ,   0,   0)
insert into funcionalidade values (148,  147, 'Inserir Fornecedor'                  , 'S', 'fornecedor/inserirFornecedor'                            , 800, 600)
insert into funcionalidade values (149,  147, 'Manter Fornecedor'                   , 'S', 'fornecedor/consultarFornecedor'                          , 800, 600)
insert into funcionalidade values (150,  100, 'Fabricantes'                         , 'S', NULL                                                      , 800, 600)
insert into funcionalidade values (151,  150, 'Inserir Fabricante'                  , 'S', 'fabricante/inserirFabricante'                            , 800, 600)
insert into funcionalidade values (152,  150, 'Manter Fabricante'                   , 'S', 'fabricante/consultarFabricante'                          , 800, 600)

insert into funcionalidade values (200, NULL, 'Operações'                           , 'S', NULL                                                       , 0    , 0   )
insert into funcionalidade values (201,  200, 'Liberar Carga de Dados'              , 'S', 'lote/liberaDados'                                         , 800  , 300 )
insert into funcionalidade values (202,  200, 'Entrada de Produto'                  , 'S', NULL                                                       , 0    , 0   )
insert into funcionalidade values (203,  202, 'Inserir Entrada de Produtos'         , 'S', 'entradaProduto/inserirEntradaProduto'                     , 800  , 600 )
insert into funcionalidade values (204,  202, 'Consultar Entrada de Produtos'       , 'S', 'entradaProduto/consultarEntradaProduto'                   , 800  , 600 )
insert into funcionalidade values (205,  200, 'Movimentações'                       , 'S', NULL                                                       , 800  , 600 )
insert into funcionalidade values (206,  205, 'Produto entre Estoques'              , 'S', NULL                                                       , 0    , 0   )
insert into funcionalidade values (207,  206, 'Inserir Movimentação'                , 'S', 'movimentacaoEstoque/inserirMovimentacaoEstoque'           , 800  , 600 )
insert into funcionalidade values (208,  206, 'Consultar Movimentação'              , 'S', 'movimentacaoEstoque/consultarMovimentacaoEstoque'         , 800  , 600 )
insert into funcionalidade values (209,  205, 'Ajuste de Estoque'                   , 'S', NULL                                                       , 0    , 0   )
insert into funcionalidade values (210,  209, 'Inserir Ajustes de Estoque'          , 'S', 'ajusteEstoque/inserirAjusteEstoque'                       , 800  , 600 )
insert into funcionalidade values (211,  209, 'Consultar Ajuste de Estoque'         , 'S', 'ajusteEstoque/consultarAjusteEstoque'                     , 800  , 600 )
insert into funcionalidade values (212,  200, 'Transações'                          , 'S', NULL                                                       , 0    , 0   )
insert into funcionalidade values (213,  212, 'Manter Transação'                    , 'S', 'transacao/consultarTransacao'                             , 800  , 770 )
insert into funcionalidade values (214,  200, 'Devoluções'                          , 'S', NULL                                                       , 0    , 0   )
insert into funcionalidade values (215,  214, 'Inserir Devolução'                   , 'S', 'devolucao/inserirDevolucao'                               , 800  , 600 )
insert into funcionalidade values (216,  214, 'Manter Devolução'                    , 'S', 'devolucao/consultarDevolucao'                             , 800  , 600 )

insert into funcionalidade values (300, NULL, 'Relatórios'                          , 'S', NULL                                                       , 800  , 600 )
insert into funcionalidade values (301,  300, 'Analítico de Entradas'               , 'S', 'reports/relatorioAnaliticoEntrada'                        , 800  , 300 )
insert into funcionalidade values (302,  300, 'Analítico de Vendas'                 , 'S', 'reports/relatorioAnaliticoFechamentoVendas'               , 800  , 300 )
insert into funcionalidade values (303,  300, 'Analítico de Movimentação de Estoque', 'S', 'reports/relatorioAnaliticoMovimentacaoEstoque'            , 800  , 300 )
insert into funcionalidade values (304,  300, 'Analítico de Operações de Devolução' , 'S', 'reports/relatorioAnaliticoOperacoesDevolucao'             , 800  , 300 )
insert into funcionalidade values (305,  300, 'ABC Vendas'                          , 'S', 'reports/relatorioABCVendas'                               , 800  , 350 )
insert into funcionalidade values (306,  300, 'Fechamento Caixa'                    , 'S', NULL                                                       , 0    , 0   )
insert into funcionalidade values (307,  306, 'Geral'                               , 'S', 'reports/relatorioFechamentoCaixaGeral'                    , 800  , 300 )
insert into funcionalidade values (308,  306, 'Operador'                            , 'S', 'reports/relatorioFechamentoCaixaOperador'                 , 800  , 350 )
insert into funcionalidade values (309,  300, 'Comissão Por Vendedor'               , 'S', 'reports/relatorioComissaoPorVendedor'                     , 800  , 350 )
insert into funcionalidade values (310,  300, 'Estoque Atual'                       , 'S', 'reports/relatorioEstoqueAtual'                            , 800  , 350 )
insert into funcionalidade values (311,  300, 'Lucro Bruto'                         , 'S', 'reports/relatorioLucroBruto'                              , 800  , 350 )
insert into funcionalidade values (312,  300, 'Contas à Pagar'                      , 'S', 'reports/relatorioAnaliticoLancamentosContasAPagar'        , 800  , 500 )
insert into funcionalidade values (313,  300, 'Contas à Receber'                    , 'S', 'reports/relatorioAnaliticoLancamentosContasAReceber'      , 800  , 500 )

insert into funcionalidade values (400, NULL, 'Financeiro'                          , 'S', NULL                                                       , 0    , 0   )
insert into funcionalidade values (401,  400, 'Lançamentos'                         , 'S', NULL                                                       , 0    , 0   )
insert into funcionalidade values (402,  401, 'Conta à Pagar'                       , 'S', 'lancamento/inserirLancamentoContaAPagar'                  , 800  , 600 )
insert into funcionalidade values (403,  401, 'Conta à Receber'                     , 'S', 'lancamento/inserirLancamentoContaAReceber'                , 800  , 600 )
insert into funcionalidade values (404,  401, 'Consultar Lançamentos'               , 'S', 'lancamento/consultarLancamento'                           , 800  , 600 )
insert into funcionalidade values (405,  400, 'Grupo de Lançamentos'                , 'S', NULL                                                       , 0    , 0   )
insert into funcionalidade values (406,  405, 'Inserir Grupo de Lançamento'         , 'S', 'grupoLancamento/inserirGrupoLancamento'                   , 800  , 600 )
insert into funcionalidade values (407,  405, 'Consultar Grupo de Lançamento'       , 'S', 'grupoLancamento/consultarGrupoLancamento'                 , 800  , 600 )
insert into funcionalidade values (408,  400, 'Baixa de Lançamentos'                , 'S', 'baixaLancamento/consultarBaixaLancamento'                 , 800  , 600 )
insert into funcionalidade values (409,  400, 'Movimentação Bancária'               , 'S', NULL                                                       , 800  , 600 )
insert into funcionalidade values (410,  409, 'Inserir Movimentação'                , 'S', 'movimentacaoBancaria/inserirMovimentacaoBancaria'         , 800  , 600 )
insert into funcionalidade values (411,  409, 'Manter Movimentação'                 , 'S', 'movimentacaoBancaria/consultarMovimentacaoBancaria'       , 800  , 600 )
insert into funcionalidade values (412,  400, 'Conta Corrente'                      , 'S', NULL                                                       , 800  , 600 )
insert into funcionalidade values (413,  412, 'Inserir Conta Corrente'              , 'S', 'contaCorrente/inserirContaCorrente'                       , 800  , 600 )
insert into funcionalidade values (414,  412, 'Manter Conta Corrente'               , 'S', 'contaCorrente/consultarContaCorrente'                     , 800  , 600 )
                                
insert into funcionalidade values (500, NULL, 'Produção'                            , 'S', NULL                                                       , 0    , 0   );
insert into funcionalidade values (501,  500, 'Inserir Lote'                        , 'S', 'producao/inserirProducao'                                 , 800  , 600 );
insert into funcionalidade values (502,  500, 'Manter Lote'                         , 'S', 'producao/consultarProducao'                               , 800  , 600 );
                                                                                                                                                                                                     
insert into funcionalidade values (999, NULL, 'Logout'                              , 'S', 'logout'                                                   , 0    , 0   )

insert into perfil_funcionalidade
select 1, id from funcionalidade