delete from entrada_produto
delete from estoque_produto
delete from ajuste_estoque
delete from autorizacao_cartao_proprio
delete from cliente_pagto
delete from cliente_transacao
delete from dados_lote
delete from historico_cliente
delete from movimentacao_estoque
delete from produto_operac_item_registrado
delete from evento_operacao_item_registrado
delete from evento_operacao
delete from operacao_devolucao
delete from operacao
delete from produto_entrada_produto
delete from produto_item_registrado
delete from produto_movimentacao_estoque
delete from evento_item_registrado
delete from evento_item_pag_cartao_off
delete from evento_item_pag_cartao_proprio
delete from evento_item_pag_cheque_pre
delete from evento_item_pagamento_cheque
delete from evento_item_pagamento_troca
delete from evento_item_pagamento
delete from evento_transacao
delete from transacao_abertura
delete from transacao_cancelamento
delete from transacao_entrada_operador
delete from transacao_fechamento_x
delete from transacao_fechamento_z
delete from transacao_pagamento
delete from transacao_pagto_cartao_proprio
delete from transacao_resuprimento
delete from transacao_sangria
delete from transacao_venda
delete from transacao