delete from perfil_funcionalidade

delete from funcionalidade

insert into funcionalidade (id, descricao, situacao, largura, altura) values(1, 'Cadastros', 'S', 0, 0)
insert into funcionalidade (id, descricao, situacao, largura, altura) values(39, 'Operações', 'S', 0, 0)
insert into funcionalidade (id, descricao, situacao, largura, altura) values(41, 'Clientes', 'S', 0, 0)
insert into funcionalidade (id, descricao, situacao, largura, altura) values(67, 'Relatórios', 'S', 800, 600)
insert into funcionalidade (id, id_func_superior, descricao, situacao, largura, altura) values(2, 1, 'Usuário', 'S', 0, 0)
insert into funcionalidade (id, id_func_superior, descricao, situacao, largura, altura) values(5, 1, 'Perfil', 'S', 0, 0)
insert into funcionalidade (id, id_func_superior, descricao, situacao, largura, altura) values(8, 1, 'Loja', 'S', 0, 0)
insert into funcionalidade (id, id_func_superior, descricao, situacao, largura, altura) values(11, 1, 'Componente', 'S', 0, 0)
insert into funcionalidade (id, id_func_superior, descricao, situacao, largura, altura) values(14, 1, 'Administração de Produtos', 'S', 0, 0)
insert into funcionalidade (id, id_func_superior, descricao, situacao, largura, altura) values(30, 1, 'Forma de Recebimento', 'S', 0, 0)
insert into funcionalidade (id, id_func_superior, descricao, situacao, largura, altura) values(33, 1, 'Plano de Pagamento', 'S', 0, 0)
insert into funcionalidade (id, id_func_superior, descricao, situacao, largura, altura) values(36, 1, 'Estoque', 'S', 0, 0)
insert into funcionalidade (id, id_func_superior, descricao, situacao, largura, altura) values(54, 1, 'Autorizadora', 'S', 0, 0)
insert into funcionalidade (id, id_func_superior, descricao, situacao, largura, altura) values(57, 1, 'Plano de Pagamento Cheque Pré-Datado', 'S', 0, 0)
insert into funcionalidade (id, id_func_superior, descricao, situacao, largura, altura) values(63, 1, 'Fornecedores', 'S', 0, 0)
insert into funcionalidade (id, id_func_superior, descricao, situacao, largura, altura) values(78, 1, 'Fabricantes', 'S', 800, 600)
insert into funcionalidade (id, id_func_superior, descricao, situacao, largura, altura) values(15, 14, 'Grupo de Produto', 'S', 0, 0)
insert into funcionalidade (id, id_func_superior, descricao, situacao, largura, altura) values(18, 14, 'Tipo de Produto', 'S', 0, 0)
insert into funcionalidade (id, id_func_superior, descricao, situacao, largura, altura) values(21, 14, 'Produto', 'S', 0, 0)
insert into funcionalidade (id, id_func_superior, descricao, situacao, largura, altura) values(24, 14, 'Unidade', 'S', 0, 0)
insert into funcionalidade (id, id_func_superior, descricao, situacao, largura, altura) values(27, 14, 'Imposto', 'S', 0, 0)
insert into funcionalidade (id, id_func_superior, descricao, situacao, largura, altura) values(60, 39, 'Pagamento de Contas', 'S', 0, 0)
insert into funcionalidade (id, id_func_superior, descricao, situacao, largura, altura) values(66, 39, 'Movimentações', 'S', 800, 600)
insert into funcionalidade (id, id_func_superior, descricao, situacao, largura, altura) values(68, 39, 'Transações', 'S', 0, 0)
insert into funcionalidade (id, id_func_superior, descricao, situacao, largura, altura) values(71, 39, 'Devoluções', 'S', 0, 0)
insert into funcionalidade (id, id_func_superior, descricao, situacao, largura, altura) values(42, 41, 'Administração de Clientes', 'S', 0, 0)
insert into funcionalidade (id, id_func_superior, descricao, situacao, largura, altura) values(45, 66, 'Entrada de Produto', 'S', 0, 0)
insert into funcionalidade (id, id_func_superior, descricao, situacao, largura, altura) values(48, 66, 'Movimentação de Produto entre Estoques', 'S', 0, 0)
insert into funcionalidade (id, id_func_superior, descricao, situacao, largura, altura) values(51, 66, 'Ajuste de Estoque', 'S', 0, 0)
insert into funcionalidade (id, id_func_superior, descricao, situacao, url, largura, altura) values(3, 2, 'Inserir Usuário', 'S', 'usuario/inserirUsuario', 800, 500)
insert into funcionalidade (id, id_func_superior, descricao, situacao, url, largura, altura) values(4, 2, 'Manter Usuário', 'S', 'usuario/consultarUsuario', 800, 500)
insert into funcionalidade (id, id_func_superior, descricao, situacao, url, largura, altura) values(6, 5, 'Inserir Perfil', 'S', 'perfil/inserirPerfil', 800, 500)
insert into funcionalidade (id, id_func_superior, descricao, situacao, url, largura, altura) values(7, 5, 'Manter Perfil', 'S', 'perfil/consultarPerfil', 800, 500)
insert into funcionalidade (id, id_func_superior, descricao, situacao, url, largura, altura) values(9, 8, 'Inserir Loja', 'S', 'loja/inserirLoja', 800, 500)
insert into funcionalidade (id, id_func_superior, descricao, situacao, url, largura, altura) values(10, 8, 'Manter Loja', 'S', 'loja/consultarLoja', 800, 500)
insert into funcionalidade (id, id_func_superior, descricao, situacao, url, largura, altura) values(12, 11, 'Inserir Componente', 'S', 'componente/inserirComponente', 800, 450)
insert into funcionalidade (id, id_func_superior, descricao, situacao, url, largura, altura) values(13, 11, 'Manter Componente', 'S', 'componente/consultarComponente', 800, 450)
insert into funcionalidade (id, id_func_superior, descricao, situacao, url, largura, altura) values(16, 15, 'Inserir Grupo Produto', 'S', 'grupoProduto/inserirGrupoProduto', 800, 600)
insert into funcionalidade (id, id_func_superior, descricao, situacao, url, largura, altura) values(17, 15, 'Manter Grupo de Produto', 'S', 'grupoProduto/consultarGrupoProduto', 800, 600)
insert into funcionalidade (id, id_func_superior, descricao, situacao, url, largura, altura) values(19, 18, 'Inserir Tipo de Produto', 'S', 'tipoProduto/inserirTipoProduto', 800, 600)
insert into funcionalidade (id, id_func_superior, descricao, situacao, url, largura, altura) values(20, 18, 'Manter Tipo de Produto', 'S', 'tipoProduto/consultarTipoProduto', 800, 600)
insert into funcionalidade (id, id_func_superior, descricao, situacao, url, largura, altura) values(22, 21, 'Inserir Produto', 'S', 'produto/inserirProduto', 550, 450)
insert into funcionalidade (id, id_func_superior, descricao, situacao, url, largura, altura) values(23, 21, 'Manter Produto', 'S', 'produto/consultarProduto', 800, 600)
insert into funcionalidade (id, id_func_superior, descricao, situacao, url, largura, altura) values(25, 24, 'Inserir Unidade', 'S', 'unidade/inserirUnidade', 800, 600)
insert into funcionalidade (id, id_func_superior, descricao, situacao, url, largura, altura) values(26, 24, 'Manter Unidade', 'S', 'unidade/consultarUnidade', 800, 600)
insert into funcionalidade (id, id_func_superior, descricao, situacao, url, largura, altura) values(28, 27, 'Inserir Imposto', 'S', 'imposto/inserirImposto', 800, 600)
insert into funcionalidade (id, id_func_superior, descricao, situacao, url, largura, altura) values(29, 27, 'Manter Imposto', 'S', 'imposto/consultarImposto', 800, 600)
insert into funcionalidade (id, id_func_superior, descricao, situacao, url, largura, altura) values(31, 30, 'Inserir Forma de Recebimento', 'S', 'formaRecebimento/inserirFormaRecebimento', 800, 600)
insert into funcionalidade (id, id_func_superior, descricao, situacao, url, largura, altura) values(32, 30, 'Manter Forma de Recebimento', 'S', 'formaRecebimento/consultarFormaRecebimento', 800, 600)
insert into funcionalidade (id, id_func_superior, descricao, situacao, url, largura, altura) values(34, 33, 'Inserir Plano de Pagamento', 'S', 'planoPagamento/inserirPlanoPagamento', 800, 600)
insert into funcionalidade (id, id_func_superior, descricao, situacao, url, largura, altura) values(35, 33, 'Manter Plano de Pagamento', 'S', 'planoPagamento/consultarPlanoPagamento', 800, 600)
insert into funcionalidade (id, id_func_superior, descricao, situacao, url, largura, altura) values(37, 36, 'Inserir Estoque', 'S', 'estoque/inserirEstoque', 800, 600)
insert into funcionalidade (id, id_func_superior, descricao, situacao, url, largura, altura) values(38, 36, 'Manter Estoque', 'S', 'estoque/consultarEstoque', 800, 600)
insert into funcionalidade (id, id_func_superior, descricao, situacao, url, largura, altura) values(40, 39, 'Liberar Carga de Dados', 'S', 'lote/liberaDados', 800, 300)
insert into funcionalidade (id, id_func_superior, descricao, situacao, url, largura, altura) values(43, 42, 'Inserir Cliente', 'S', 'cliente/inserirCliente', 800, 500)
insert into funcionalidade (id, id_func_superior, descricao, situacao, url, largura, altura) values(44, 42, 'Manter Cliente', 'S', 'cliente/consultarCliente', 800, 500)
insert into funcionalidade (id, id_func_superior, descricao, situacao, url, largura, altura) values(46, 45, 'Inserir Entrada de Produtos', 'S', 'entradaProduto/inserirEntradaProduto', 800, 600)
insert into funcionalidade (id, id_func_superior, descricao, situacao, url, largura, altura) values(47, 45, 'Consultar Entrada de Produtos', 'S', 'entradaProduto/consultarEntradaProduto', 800, 600)
insert into funcionalidade (id, id_func_superior, descricao, situacao, url, largura, altura) values(49, 48, 'Inserir Movimentação  entre Estoques', 'S', 'movimentacaoEstoque/inserirMovimentacaoEstoque', 800, 600)
insert into funcionalidade (id, id_func_superior, descricao, situacao, url, largura, altura) values(50, 48, 'Consultar Movimentação  entre Estoques', 'S', 'movimentacaoEstoque/consultarMovimentacaoEstoque', 800, 600)
insert into funcionalidade (id, id_func_superior, descricao, situacao, url, largura, altura) values(52, 51, 'Inserir Ajustes de Estoque', 'S', 'ajusteEstoque/inserirAjusteEstoque', 800, 600)
insert into funcionalidade (id, id_func_superior, descricao, situacao, url, largura, altura) values(53, 51, 'Consultar Ajuste de Estoque', 'S', 'ajusteEstoque/consultarAjusteEstoque', 800, 600)
insert into funcionalidade (id, id_func_superior, descricao, situacao, url, largura, altura) values(55, 54, 'Inserir Autorizadora', 'S', 'autorizadora/inserirAutorizadora', 800, 600)
insert into funcionalidade (id, id_func_superior, descricao, situacao, url, largura, altura) values(56, 54, 'Consultar Autorizadora', 'S', 'autorizadora/consultarAutorizadora', 800, 600)
insert into funcionalidade (id, id_func_superior, descricao, situacao, url, largura, altura) values(58, 57, 'Inserir Plano de Pagamento Cheque Pré-Datado', 'S', 'planoPagamentoChequePre/inserirPlanoPagamentoChequePre', 800, 600)
insert into funcionalidade (id, id_func_superior, descricao, situacao, url, largura, altura) values(59, 57, 'Manter Plano de Pagamento Cheque Pré-Datado', 'S', 'planoPagamentoChequePre/consultarPlanoPagamentoChequePre', 800, 600)
insert into funcionalidade (id, id_func_superior, descricao, situacao, url, largura, altura) values(61, 60, 'Inserir Pagamento', 'S', 'clientePagamento/inserirClientePagamento', 800, 600)
insert into funcionalidade (id, id_func_superior, descricao, situacao, url, largura, altura) values(62, 60, 'Consultar Pagamentos', 'S', 'clientePagamento/consultarClientePagamento', 800, 600)
insert into funcionalidade (id, id_func_superior, descricao, situacao, url, largura, altura) values(64, 63, 'Inserir Fornecedor', 'S', 'fornecedor/inserirFornecedor', 800, 600)
insert into funcionalidade (id, id_func_superior, descricao, situacao, url, largura, altura) values(65, 63, 'Manter Fornecedor', 'S', 'fornecedor/consultarFornecedor', 800, 600)
insert into funcionalidade (id, id_func_superior, descricao, situacao, url, largura, altura) values(74, 67, 'Analítico de Entradas', 'S', 'reports/relatorioAnaliticoEntrada', 800, 300)
insert into funcionalidade (id, id_func_superior, descricao, situacao, url, largura, altura) values(75, 67, 'Analítico de Vendas', 'S', 'reports/relatorioAnaliticoFechamentoVendas', 800, 300)
insert into funcionalidade (id, id_func_superior, descricao, situacao, url, largura, altura) values(76, 67, 'Analítico de Movimentação de Estoque', 'S', 'reports/relatorioAnaliticoMovimentacaoEstoque', 800, 300)
insert into funcionalidade (id, id_func_superior, descricao, situacao, url, largura, altura) values(77, 67, 'Analítico de Operações de Devolução', 'S', 'reports/relatorioAnaliticoOperacoesDevolucao', 800, 300)
insert into funcionalidade (id, id_func_superior, descricao, situacao, url, largura, altura) values(69, 68, 'Inserir Transação', 'S', 'transacao/inserirTransacao', 800, 770)
insert into funcionalidade (id, id_func_superior, descricao, situacao, url, largura, altura) values(70, 68, 'Manter Transação', 'S', 'transacao/consultarTransacao', 800, 770)
insert into funcionalidade (id, id_func_superior, descricao, situacao, url, largura, altura) values(72, 71, 'Inserir Devolução', 'S', 'devolucao/inserirDevolucao', 800, 600)
insert into funcionalidade (id, id_func_superior, descricao, situacao, url, largura, altura) values(73, 71, 'Manter Devolução', 'S', 'devolucao/consultarDevolucao', 800, 600)
insert into funcionalidade (id, id_func_superior, descricao, situacao, url, largura, altura) values(79, 78, 'Inserir Fabricante', 'S', 'fabricante/inserirFabricante', 800, 600)
insert into funcionalidade (id, id_func_superior, descricao, situacao, url, largura, altura) values(80, 78, 'Manter Fabricante', 'S', 'fabricante/consultarFabricante', 800, 600)
insert into funcionalidade (id, id_func_superior, descricao, situacao, url, largura, altura) values(81, 39, 'Liberar Nova Base', 'S', 'cargabase/liberaCargaBase', 800, 300)
insert into funcionalidade (id, descricao, situacao, url, largura, altura) values(999, 'Logout', 'S', 'logout', 0, 0)

insert into perfil_funcionalidade
select 1, id from funcionalidade